# Generated by Django 3.0.1 on 2020-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
