# Generated by Django 3.0.1 on 2020-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0002_auto_20200104_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static', width_field=120),
        ),
    ]
