# Generated by Django 3.0.1 on 2020-02-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0002_auto_20200203_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
