# Generated by Django 3.0.1 on 2020-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0003_auto_20200104_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static', width_field='120'),
        ),
    ]
